CI: updates #7

diff --git a/.github/workflows/weekly-ci-cc-llvm-mingw.yml b/.github/workflows/weekly-ci-cc-llvm-mingw.yml
--- a/.github/workflows/weekly-ci-cc-llvm-mingw.yml
+++ b/.github/workflows/weekly-ci-cc-llvm-mingw.yml
@@ -42,9 +42,36 @@ jobs:
           - name: llvm-mingw-20240417-ucrt
             llvm_version: 18.1.4
             url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240417/llvm-mingw-20240417-ucrt-ubuntu-20.04-x86_64.tar.xz'
+# BROKEN for i686 msvcrt; see https://github.com/mstorsjo/llvm-mingw/issues/427
+#         - name: llvm-mingw-20240502-msvcrt
+#           llvm_version: 18.1.5
+#           url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240502/llvm-mingw-20240502-msvcrt-ubuntu-20.04-x86_64.tar.xz'
+          - name: llvm-mingw-20240502-ucrt
+            llvm_version: 18.1.5
+            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240502/llvm-mingw-20240502-ucrt-ubuntu-20.04-x86_64.tar.xz'
+          - name: llvm-mingw-20240518-msvcrt
+            llvm_version: 18.1.6
+            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240518/llvm-mingw-20240518-msvcrt-ubuntu-20.04-x86_64.tar.xz'
+          - name: llvm-mingw-20240518-ucrt
+            llvm_version: 18.1.6
+            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240518/llvm-mingw-20240518-ucrt-ubuntu-20.04-x86_64.tar.xz'
     name: ${{ format('{0} {1}', matrix.name, matrix.llvm_version) }}
     runs-on: ubuntu-latest
+    container: ubuntu:24.04
+    env:
+      CMAKE_SYSTEM_NAME: Windows
+      xflags: -D_WIN32_WINNT=0x0400
     steps:
+      - name: ${{ format('Install packages {0}', job.container) }}
+        if: ${{ job.container }}
+        run: |
+          dpkg --add-architecture i386
+          apt-get update && apt-get upgrade -y
+          apt-get install -y --no-install-recommends bash ca-certificates cmake curl file git make tar time wine wine32:i386 wine64 xz-utils
+          git config --global --add safe.directory '*' # needed when running in a container
+          ls -l /usr/bin/wine*
+          mkdir -p -v ~/.wine
+          wineboot --init
       - name: 'Check out code'
         uses: actions/checkout@v4
         with: { submodules: true }
@@ -52,49 +79,80 @@ jobs:
         run: |
           mkdir -p -v ~/.local/bin
           cd ~/.local/bin
-          wget -q '${{ matrix.url }}'
+          curl -sS -L -O '${{ matrix.url }}'
           ls -l ./llvm-mingw*.tar.*
           tar -xoaf ./llvm-mingw*.tar.*
           rm ./llvm-mingw*.tar.*
           # update PATH
           cd ./llvm-mingw*/bin
           echo "PATH=$PWD:$PATH" >> $GITHUB_ENV
+
       - name: 'Build clang aarch64'
         run: |
-          export CC="aarch64-w64-mingw32-clang -static" CXX="aarch64-w64-mingw32-clang++ -static"
-          CC="$CC -D_WIN32_WINNT=0x0400"; CXX="$CXX -D_WIN32_WINNT=0x0400"
-          export CMAKE_SYSTEM_NAME=Windows
-          make UPX_XTARGET=llvm-mingw/aarch64-w64-mingw32-clang xtarget/debug xtarget/release
+          export CC="aarch64-w64-mingw32-clang $xflags" CXX="aarch64-w64-mingw32-clang++ $xflags"
+          make UPX_XTARGET=llvm-mingw/aarch64-w64-mingw32-clang xtarget/all
+      - name: 'Build clang aarch64 static'
+        if: success() || failure() # run this step even if the previous step failed
+        run: |
+          export CC="aarch64-w64-mingw32-clang -static $xflags" CXX="aarch64-w64-mingw32-clang++ -static $xflags"
+          make UPX_XTARGET=llvm-mingw/aarch64-w64-mingw32-clang-static xtarget/all
+
       - name: 'Build clang armv7'
         if: success() || failure() # run this step even if the previous step failed
         run: |
-          export CC="armv7-w64-mingw32-clang -static" CXX="armv7-w64-mingw32-clang++ -static"
-          CC="$CC -D_WIN32_WINNT=0x0400"; CXX="$CXX -D_WIN32_WINNT=0x0400"
-          export CMAKE_SYSTEM_NAME=Windows
-          make UPX_XTARGET=llvm-mingw/armv7-w64-mingw32-clang xtarget/debug xtarget/release
+          export CC="armv7-w64-mingw32-clang $xflags" CXX="armv7-w64-mingw32-clang++ $xflags"
+          make UPX_XTARGET=llvm-mingw/armv7-w64-mingw32-clang xtarget/all
+      - name: 'Build clang armv7 static'
+        if: success() || failure() # run this step even if the previous step failed
+        run: |
+          export CC="armv7-w64-mingw32-clang -static $xflags" CXX="armv7-w64-mingw32-clang++ -static $xflags"
+          make UPX_XTARGET=llvm-mingw/armv7-w64-mingw32-clang-static xtarget/all
+
       - name: 'Build clang i686'
         if: success() || failure() # run this step even if the previous step failed
         run: |
-          export CC="i686-w64-mingw32-clang -static" CXX="i686-w64-mingw32-clang++ -static"
-          CC="$CC -D_WIN32_WINNT=0x0400"; CXX="$CXX -D_WIN32_WINNT=0x0400"
-          export CMAKE_SYSTEM_NAME=Windows CMAKE_CROSSCOMPILING_EMULATOR=wine
-          make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang xtarget/debug xtarget/release
+          export CC="i686-w64-mingw32-clang $xflags" CXX="i686-w64-mingw32-clang++ $xflags"
+          export CMAKE_CROSSCOMPILING_EMULATOR=wine
+          export UPX_CONFIG_DISABLE_RUN_PACKED_TEST=ON # TODO FIXME
+          make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang xtarget/all
+      - name: 'Build clang i686 static'
+        if: success() || failure() # run this step even if the previous step failed
+        run: |
+          export CC="i686-w64-mingw32-clang -static $xflags" CXX="i686-w64-mingw32-clang++ -static $xflags"
+          export CMAKE_CROSSCOMPILING_EMULATOR=wine
+          export UPX_CONFIG_DISABLE_RUN_PACKED_TEST=ON # TODO FIXME
+          make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang-static xtarget/all
+
       - name: 'Build clang x86_64'
         if: success() || failure() # run this step even if the previous step failed
         run: |
-          export CC="x86_64-w64-mingw32-clang -static" CXX="x86_64-w64-mingw32-clang++ -static"
-          CC="$CC -D_WIN32_WINNT=0x0400"; CXX="$CXX -D_WIN32_WINNT=0x0400"
-          export CMAKE_SYSTEM_NAME=Windows CMAKE_CROSSCOMPILING_EMULATOR=wine64
-          make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang xtarget/debug xtarget/release
-      - name: 'Make artifact'
+          export CC="x86_64-w64-mingw32-clang $xflags" CXX="x86_64-w64-mingw32-clang++ $xflags"
+          export CMAKE_CROSSCOMPILING_EMULATOR=wine
+          make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang xtarget/all
+      - name: 'Build clang x86_64 static'
+        if: success() || failure() # run this step even if the previous step failed
         run: |
+          export CC="x86_64-w64-mingw32-clang -static $xflags" CXX="x86_64-w64-mingw32-clang++ -static $xflags"
+          export CMAKE_CROSSCOMPILING_EMULATOR=wine
+          make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang-static xtarget/all
+
+      - name: 'Make artifact'
+        shell: bash
+        run: |
+          ls -l build/*/*/*/upx.exe
+          file  build/*/*/*/upx.exe || true
+          size  build/*/*/*/upx.exe || true
           N=$(echo "upx-${GITHUB_REF_NAME}-${GITHUB_SHA:0:7}-weekly-ci-${{ matrix.name }}-${{ matrix.llvm_version }}" | sed 's/[^0-9a-zA-Z_.-]/-/g')
           mkdir -p "tmp/artifact/$N"
           (cd build && cp -ai --parents */*/*/upx.exe "../tmp/artifact/$N")
-          # GitHub Actions magic: set "artifact_name" environment value for use in next step
           echo "artifact_name=$N" >> $GITHUB_ENV
       - name: ${{ format('Upload artifact {0}', env.artifact_name) }}
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.artifact_name }}
           path: tmp/artifact
+
+      - name: 'Run ctest tests i686 static with Wine'
+        run: make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang-static xtarget/all+test
+      - name: 'Run ctest tests x86_64 static with Wine'
+        run: make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang-static xtarget/all+test
